<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newstocontentrelation"
 *
 * Auto generated by Extension Builder 2014-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News to Content Relation',
	'description' => 'Moves the embedded news (bodytext) content to a content elements and adds this as content element relation to the news record.',
	'category' => 'plugin',
	'author' => 'Philipp Gampe',
	'author_email' => 'philipp.gampe@typo3.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>